# Generated by Django 3.1.7 on 2021-03-11 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_basket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Basket',
        ),
    ]
