# Generated by Django 3.1.7 on 2021-03-17 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date',
        ),
    ]
